@extends('layouts.app')

@section('title', 'Bank Soal CBT')

@section('content')
<div class="container-fluid"><div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="h3 mb-1 fw-bold">Bank Soal CBT</h1><p class="text-muted mb-0">Monitor soal dan kuis yang dibuat guru.</p></div></div>
    <x-page-guide>Halaman ini hanya untuk memantau soal & kuis yang dibuat guru. Untuk membuat atau mengubah soal/kuis, gunakan akun guru yang bersangkutan.</x-page-guide>
    <div class="card shadow-sm mb-4"><div class="card-header bg-white"><h6 class="fw-bold mb-0">Daftar Kuis</h6></div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead class="table-light"><tr><th>Judul</th><th>Mapel</th><th>Kelas</th><th>Jumlah Soal</th><th>Durasi</th><th>Status</th></tr></thead><tbody>@forelse($quizzes as $quiz)<tr><td class="fw-semibold">{{ $quiz->title }}</td><td>{{ $quiz->subject->name }}</td><td>{{ $quiz->classroom->name }}</td><td>{{ $quiz->questions->count() }}</td><td>{{ $quiz->duration_minutes }} menit</td><td><span class="badge {{ $quiz->is_published ? 'bg-success' : 'bg-secondary' }}">{{ $quiz->is_published ? 'Aktif' : 'Draft' }}</span></td></tr>@empty<tr><td colspan="6" class="text-center text-muted py-4">Belum ada kuis.</td></tr>@endforelse</tbody></table></div></div>
    <div class="card shadow-sm"><div class="card-header bg-white"><h6 class="fw-bold mb-0">Semua Soal</h6></div><div class="card-body"><div class="row g-3">@forelse($questions as $question)<div class="col-lg-6"><div class="border rounded p-3 h-100"><span class="badge bg-primary">{{ $question->subject->name }}</span><div class="fw-semibold mt-2">{{ $question->question }}</div>@if($question->media_path)@if($question->media_type === 'video')<video src="{{ Storage::url($question->media_path) }}" class="img-fluid rounded mt-2" controls></video>@else<img src="{{ Storage::url($question->media_path) }}" class="img-fluid rounded mt-2" alt="Media soal">@endif @endif<ol type="A" class="small text-muted mb-0 mt-2">@foreach($question->options as $option)<li>{{ $option }}</li>@endforeach</ol><div class="small text-success mt-2">Kunci: {{ $question->correct_answer }}</div></div></div>@empty<div class="col-12 text-center text-muted py-4">Belum ada soal.</div>@endforelse</div></div></div>
</div>
@endsection
